# Generated by Django 4.2.7 on 2024-02-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_medicine_photo'),
        ('users', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, help_text='Товари в корзині', related_name='cart', to='main.medicine'),
        ),
    ]
