# Generated by Django 4.2.7 on 2024-02-09 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_medicine_photo'),
        ('users', '0005_user_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='Коментарій')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.medicine')),
                ('user', models.ForeignKey(blank=True, help_text='Користувач', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Коментарій',
                'verbose_name_plural': 'Коментарії',
                'db_table': 'comment',
            },
        ),
    ]
