# Generated by Django 4.2.7 on 2024-02-09 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_comment_date_alter_comment_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.AddField(
            model_name='comment',
            name='date_posted',
            field=models.DateField(default=datetime.date.today, help_text='Дата'),
        ),
    ]
