# Generated by Django 4.2.7 on 2023-12-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CountryOfOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва препарату', max_length=100)),
                ('price', models.FloatField(blank=True, default=0, help_text='Ціна')),
                ('photo', models.TextField(blank=True, default='', help_text='Фото препарату')),
                ('is_prescription_required', models.BooleanField(blank=True, default=False, help_text='Чи потрібен рецепт для покупки (Так/Ні)')),
                ('date_of_manufacture', models.DateField(blank=True, help_text='Дата виготовлення')),
                ('service_life', models.IntegerField(blank=True, help_text='Термін придатності (в місяцях)')),
                ('description', models.TextField(blank=True, help_text='Опис')),
                ('quantity', models.IntegerField(blank=True, default=0, help_text='Кількість препарату')),
                ('category', models.ManyToManyField(blank=True, help_text='Категорія препарату (протизастудні, знеболюючі і т.д.)', to='main.categories')),
                ('country_of_origin', models.ManyToManyField(blank=True, help_text='Країна-виробник', to='main.countryoforigin')),
                ('form', models.ManyToManyField(blank=True, help_text='Форма випуску препарату (сироп, таблетки і т.д.)', to='main.forms')),
                ('manufacturer', models.ManyToManyField(blank=True, help_text='Виробник препарату', to='main.manufacturers')),
            ],
        ),
    ]
