# Generated by Django 4.2.7 on 2024-01-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='countryoforigin',
            options={'verbose_name': 'Країна', 'verbose_name_plural': 'Країни'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'Форма випуску', 'verbose_name_plural': 'Форми випуску'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Виробник', 'verbose_name_plural': 'Виробники'},
        ),
    ]
