# Generated by Django 4.2.7 on 2024-02-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_alter_countryoforigin_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='photo',
            field=models.ImageField(blank=True, default='', help_text='Фото препарату', upload_to='medicines_photos'),
        ),
    ]
