# Generated by Django 4.2.7 on 2024-01-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.ManyToManyField(blank=True, default=0, help_text='Категорія препарату (протизастудні, знеболюючі і т.д.)', to='main.categories'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='country_of_origin',
            field=models.ManyToManyField(blank=True, default=0, help_text='Країна-виробник', to='main.countryoforigin'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='date_of_manufacture',
            field=models.DateField(blank=True, default='2001-01-01', help_text='Дата виготовлення'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Опис'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='form',
            field=models.ManyToManyField(blank=True, default=0, help_text='Форма випуску препарату (сироп, таблетки і т.д.)', to='main.forms'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturer',
            field=models.ManyToManyField(blank=True, default=0, help_text='Виробник препарату', to='main.manufacturers'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='service_life',
            field=models.IntegerField(blank=True, default=0, help_text='Термін придатності (в місяцях)'),
        ),
    ]
